const historyStub = [
    {
        "chapter": "Capitulo 1",
        "paragraphs": [
            "Esta historia comenzó cuando los mayores amantes de la lectura del centro educativo Pradera se hicieron mejores amigos. Alia, David, Julia y Teresa, así se llamaban. Juntos pasaron varios años en el instituto conociéndose y creando recuerdo; quedaban para hablar sobre libros, jugar a videojuegos, ver películas, hacer deporte, ir a conciertos... Se hicieron inseparables, aunque por supuesto, todo grupo tiene que tener sus dramas internos. En este caso, esa cuestión se dio cuando David se enamoró de Alia. Tenían muchas cosas en común, pero este flechazo inesperado se vio influenciado por la cantidad de tiempo que pasaban juntos jugando a videojuegos. Es aquí donde llegó un gran punto de inflexión entre los cuatro amigos, ya que a pesar de que no lo sabían, Teresa llevaba enamorada de David desde 2º. A pesar de haber sido mejores amigas desde el colegio, con el tiempo, la relación entre Teresa y Alia se desgastó y distanció por los celos ante la relación situación con David. Sin embargo, Teresa solo quería que ellos fueran felices ya que eran sus mejores amigos, por lo que a pesar de saber la verdad, siempre intentó no mostrarlo y actuar como si nunca hubiese sabido nada. Ante esto, el gran apoyo que tuvo Teresa para llevarlo, fue la cuarta integrante de este curioso grupo de amigos, Julia, quien era la única conocedora de la situación de Teresa, a pesar de que los otros dos jóvenes no eran conscientes del enamoramiento de su amiga.",
            "Pasaron 4 años en el instituto viviendo cada día juntos, compartiendo y creando recuerdos, y justo cuando ya se encontraban en 4º de la ESO, cerca de finalizar sus estudios obligatorios, David había planeado decirle a Alia sobre sus sentimientos antes de terminar, mientras que a su vez, Teresa había planeado decirle la verdad a su amiga. Sin embargo, ninguna de estas dos confesiones se pudieron llevar a cabo porque tuvo lugar un problema inesperado: un virus asoló el planeta y provocó que todos tuvieran que empezar una dura y larga cuarentena en sus casas."
        ]
    },
    {
        "chapter": "Capitulo 2",
        "paragraphs": [
            "Los días encerrados en sus respectivos hogares pasaban muy despacio. Lo único que anhelaban era tener libertad para volver a verse y vivir con normalidad. Los cuatro veían cómo sus rutinas y planes se habían desvanecido por completo. Tanto el viaje de Teresa y Julia desde España hasta Turquía en coche, como el plan de David para invitar a Alia a la Comic-Con en San Diego se tuvieron que cancelar. Los cuatro jóvenes estaban destrozados al ver todos sus planes cancelados, y fue ahí cuando empezaron a darse cuenta de que quizá no habían valorado lo suficiente lo que habían tenido siempre hasta que esta cuarentena se lo arrebató.",
            "Todo empezó con aeropuertos sin pasajeros, oficinas sin empleados, autopistas sin automóviles, calles desérticas en la ciudad y silencio, un silencio ensordecedor que aterraría a cualquier habitante de una ciudad concurrida. Todo ello provocó que la población comenzará a sentirse atrapada y desolada ante un panorama tan horrible.",
            "Los días pasaron y tras todo el caos inicial, los jóvenes protagonistas de esta historia no tuvieron más remedio que adaptarse a la nueva realidad. De los cuatro amigos, Alia fue la que mejor pudo amoldar sus hobbies a la cuarentena, sin embargo, el no tener a David al lado suyo le entristecía, sobre todo cuando miraba su agenda (un regalo de él por su cumpleaños) y veía que todos esos planes que habían hecho juntos no iban a salir del papel. Teresa siempre ha sido de esas personas a las que les gusta socializar, quedar con los amigos, irse de viaje y estar en contacto con la vida; al verse encerrada en la monotonía de la cuarentena, tuvo la idea de crear un grupo de WhatsApp para estar en contacto con sus 4 mejores amigos. Dicho grupo fue creado con el fin de que todos fueran intercambiando sus experiencias y consejos para sobrellevar este periodo de encierro. Julia era la más motivadora, siempre estaba con sus videos de ejercicios y consejos de alimentación saludable. Teresa al principio se reía mucho de su amiga y decía que sus videos no iban a funcionar, pero al final fue cediendiendo e intentando seguirlos. Esto también fue gracias a David, quien al igual que Julia era un amante del deporte, por lo que consiguió animar a Teresa para que probara a seguir el plan de ejercicio y alimentación de Julia. Por su parte, Alia no era muy afín al deporte, pero aún así intentó seguir algunos de los consejos de su amiga, sabiendo que era por su propio bien mantenerse en forma sobre todo si no podían salir de casa.",
            "Durante este periodo de cuarentena, Julia aprovechó el tiempo leyendo libros que tenía por su casa. Sin querer, un día en el que estaba haciendo limpieza, encontró el que fue su libro favorito hace mucho tiempo y decidió releerlo. Este inesperado y agradable descubrimiento quiso compartirlo a través de las redes para que sus amigos y seguidores pudiesen ver el libro que tanto le gustaba. Ya que Alia y ella tenían gustos similares de lectura, decidió escribirle para contarle sobre la trama del libro y animarla a leerlo. Tras una hora hablando sobre el libro, los personajes y la autora, Alia accedió a leérselo, aunque por supuesto tendría que esperar hasta que terminara la cuarentena para poder ir a recogerlo. Viendo a Julia con su libro, a los cuatro amigos se les ocurrió la idea de hacer un reto y leer cada uno su libro favorito en tres días para después intentar convencer a los demás para que también lo leyeran. Fue así también como los cuatro amigos se animaron a usar más las redes sociales para compartir con sus seguidores su emoción por las lecturas que estaban realizando y hacer votaciones para ver cuáles eran los libros favoritos de cada uno.",
            "Con el paso del tiempo, la situación  de encierro se fue normalizando, por lo que los cuatro amigos comenzaron a hacer planes para el futuro después de la cuarentena, cuando pudieran salir de sus casas. Todos eran conscientes de que todavía faltaba bastante tiempo hasta que les dejasen salir, pero al menos entre los cuatro se hicieron más llevadero este periodo de aislamiento."
        ]
    },
    {
        "chapter": "Capitulo 3",
        "paragraphs": [
            "Los días eran más lluviosos de lo normal e incluso caían relámpagos por las noches. A pesar de estar ya en abril, el clima había vuelto a enfriarse y el cielo permanecía encapotado cada día. Era tedioso y deprimente ver cómo todos los días parecían iguales a través del cristal. Para Julia y David la lluvia provocó una buena oportunidad de relajarse y tomar más tiempo para descansar de hacer ejercicio y así poder hacer otras actividades como ver películas, escuchar música y leer sus respectivos libros favoritos. Alia dejó algo de lado los videojuegos, ya que la conexión a Internet era muy mala por la cantidad de gente que se encontraba conectada a Internet desde sus casas cada día. Alia era consciente de que las tormentas eléctricas podían provocar que su ordenador se quemase si caía un rayo, así que optó por aceptar el reto de sus amigos y empezar la lectura de su libro preferido, el cual había dejado pendiente por culpa de su profesor de inglés, quien dejó a sus alumnos una cantidad ingente de tareas antes de que la cuarentena se lo impidiese. Por su parte, Teresa encontró su novela favorita debido a que su madre la había metido en su maleta para el viaje a Turquía que había estado preparando con Julia. Gracias a esto, al ir a deshacer el equipaje que ahora no iba a necesitar, Teresa pudo encontrarlo y ponerse con el reto acordado.",
            "Una vez encontrados todos los libros, rápidamente los muchachos hablaron y dieron el pistoletazo de salida en su grupo de WhatsApp para comenzar a leer las novelas con el objetivo de cumplir con el reto acordado, sin embargo, ninguno podía esperarse lo que el destino les tenía preparado tan solo detrás de esas finas hojas de papel escritas."
        ]
    },
    {
        "chapter": "Capitulo 4",
        "paragraphs": [
            "Eran las 3:00 de la mañana, mientras los cuatro amigos leían enfrascados en sus historias cerca ya de los respectivos finales, un relámpago alumbró toda la ciudad. Los chicos asustados, corrieron hasta sus ventanas y se dieron cuenta de que después de ese relámpago la luna tenía un brillo extraño. Todos se quedaron en silencio observando durante varios minutos cómo la luna adquiría cada vez una mayor intensidad hasta que de repente, se tornó de un color opaco. Lo que nadie sabía, y ni siquiera los expertos en astrología pudieron predecir, es que un un eclipse lunar se estaba formando sin que nadie estuviera al tanto. De repente, las luces en las casas de los chicos se apagaron de golpe y todos empezaron a sentir cómo una brisa recorría el interior de sus hogares a pesar de permanecer con las ventanas cerradas. Una bruma comenzó a brotar desde las paredes de sus respectivas habitaciones deslizándose lentamente desde el techo hasta inundar el suelo con gracilidad. Parecía algo mágico, algo que solo ocurre en las películas o cuentos. En esos momentos cada uno de los cuatro amigos comenzó a tener un déjà vu: Teresa, se acordó de haber leído hace tiempo muchos libros sobre la luna y su misticismo, por lo que cuando comenzó a ver la bruma y el eclipse, solo pudo sentir fascinación. Por otro lado, David, en uno de sus viajes a un pueblo cerca de Guatemala, había escuchado algo sobre el poder de la luna y cómo puede afectar y cambiar por completo la vida de una persona. Alia, por su parte, estaba perpleja ante este suceso, ya que recientemente había estado jugando un videojuego que trataba sobre un viajero que alcanzaba la luna y las estrellas. En el caso de Julia, ésta comenzó a recordar que en uno de sus viajes a Madrid, en el Parque de El Retiro, una gitana había leído su mano y le dijo que la luna le traería algo nuevo a su vida.",
            "Parando de golpe sus pensamientos, una luz cegadora comenzó a salir de cada uno de los cuatro libros que estaban leyendo. El resplandor cegaba a los jóvenes protagonistas, que luchaban por entender la situación. De repente, el aire que hace un rato corría libre por sus casas comenzó a agitar y tirar cosas en sus habitaciones. El viento arrastró consigo la bruma esparcida y junto a la luz blanquecina que brotaba sin control de las novelas, rodearon a los muchachos y los absorbieron hacia sus respectivos libros. Los cuatro amigos, sin poder reaccionar, se adentraron en esas páginas entintadas rumbo a lo desconocido."
        ]
    }
];

export default historyStub;